// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

export type LegalDocumentDraftDto = {
    id: string;
    type: 'USER_AGREEMENT' | 'PRIVACY_POLICY';
    version: string;
    status: 'DRAFT' | 'PUBLISHED' | 'RETIRED';
    content: string;
    contentHash: string;
    publishedAt: string | null;
    createdAt: string;
    updatedAt: string;
};

export type SaveLegalDocumentDraftDto = {
    type: 'USER_AGREEMENT' | 'PRIVACY_POLICY';
    version: string;
    content: string;
};

export type PublishLegalDocumentSetDto = {
    userAgreementDraftId: string;
    privacyPolicyDraftId: string;
};

export type StartTotpEnrollmentDto = {
    password: string;
};

export type StartedTotpEnrollmentDto = {
    secret: string;
    uri: string;
};

export type ConfirmTotpEnrollmentDto = {
    totpCode: string;
};

export type RecoveryCodesDto = {
    recoveryCodes: Array<string>;
};

export type ChangePasswordDto = {
    currentPassword: string;
    newPassword: string;
    /**
     * 已启用 TOTP 时必填
     */
    secondFactorCode?: string;
};

export type DisableTotpDto = {
    password: string;
    secondFactorCode: string;
};

export type CurrentLegalDocumentDto = {
    id: string;
    type: 'USER_AGREEMENT' | 'PRIVACY_POLICY';
    version: string;
    content: string;
    contentHash: string;
    publishedAt: string;
};

export type CaptchaChallengeDto = {
    token: string;
    mock: boolean;
};

export type RequestUserActivationCodeDto = {
    phone: string;
    captchaToken: string;
};

export type ActivationCodeDeliveryDto = {
    messageId: string;
    mock: boolean;
    /**
     * 仅 Mock 环境返回，正式短信适配器不包含此字段
     */
    debugCode?: string;
};

export type ConfirmUserActivationDto = {
    phone: string;
    /**
     * 当前用户协议与隐私政策版本 ID；首次部署未发布时为空数组
     */
    consentDocumentVersionIds: Array<string>;
};

export type SessionAccountDto = {
    accountId: string;
    displayName: string;
    kind: 'PLATFORM_ADMIN' | 'END_USER';
    tenantId: string;
    role: 'SUPER_ADMIN' | 'ORGANIZATION_ADMIN' | 'OPERATIONS_SPECIALIST' | 'PLATFORM_DASHBOARD' | 'UNIVERSITY_ADMIN' | 'COLLEGE_ADMIN' | 'PROGRAM_LEAD' | 'COUNSELOR' | 'STUDENT' | 'UNIVERSITY_DASHBOARD' | 'ENTERPRISE_ADMIN' | 'HR' | 'PROJECT_LEAD' | 'MENTOR' | 'ENTERPRISE_DASHBOARD' | 'GOVERNMENT_DASHBOARD_ADMIN' | 'GOVERNMENT_DASHBOARD';
};

export type CreatedSessionDto = {
    /**
     * 用于同源写请求的 CSRF 双提交令牌
     */
    csrfToken: string;
    expiresAt: string;
    account: SessionAccountDto;
};

export type RequestSmsLoginCodeDto = {
    phone: string;
    captchaToken: string;
};

export type SmsLoginCodeDeliveryDto = {
    messageId: string;
    mock: boolean;
    /**
     * 仅 Mock 环境返回，正式短信适配器不包含此字段
     */
    debugCode?: string;
    /**
     * 该账号已绑定 TOTP，确认短信码时还须提交第二因子
     */
    secondFactorRequired: boolean;
};

export type ConfirmSmsLoginDto = {
    phone: string;
    /**
     * 当前用户协议与隐私政策版本 ID；首次部署未发布时为空数组
     */
    consentDocumentVersionIds: Array<string>;
};

export type CreateUserPasswordSessionDto = {
    /**
     * 用户端中国大陆手机号；平台管理账号不使用本入口
     */
    phone: string;
    /**
     * 当前用户协议与隐私政策版本 ID；首次部署未发布时为空数组
     */
    consentDocumentVersionIds: Array<string>;
};

export type CreatePlatformSessionDto = {
    /**
     * 平台管理账号唯一用户名；平台账号不绑定手机号
     */
    username: string;
    /**
     * 当前用户协议与隐私政策版本 ID；首次部署未发布时为空数组
     */
    consentDocumentVersionIds: Array<string>;
};

export type StartPlatformEnrollmentDto = {
    username: string;
};

export type StartedPlatformEnrollmentDto = {
    enrollmentToken: string;
    /**
     * 仅本次响应展示，供无法扫码时手工录入验证器
     */
    totpSecret: string;
    /**
     * 供验证器扫码或导入的 otpauth URI
     */
    totpUri: string;
    expiresAt: string;
};

export type ConfirmPlatformEnrollmentDto = {
    enrollmentToken: string;
    newPassword: string;
    totpCode: string;
};

export type ConfirmedPlatformEnrollmentDto = {
    /**
     * 确认恢复码已保存时使用的一次性短效令牌
     */
    recoveryCodesConfirmationToken: string;
    expiresAt: string;
    /**
     * 仅本次响应展示，须立即离线保存
     */
    recoveryCodes: Array<string>;
};

export type FinishPlatformEnrollmentDto = {
    /**
     * 必须明确确认恢复码已离线保存，方可激活并签发会话
     */
    recoveryCodesSaved: true;
    /**
     * 当前用户协议与隐私政策版本 ID；首次部署未发布时为空数组
     */
    consentDocumentVersionIds: Array<string>;
};

export type CreatePlatformAccountDto = {
    username: string;
    displayName: string;
    role: 'ORGANIZATION_ADMIN' | 'OPERATIONS_SPECIALIST' | 'PLATFORM_DASHBOARD';
};

export type CreatedPlatformAccountDto = {
    accountId: string;
    username: string;
    displayName: string;
    role: 'ORGANIZATION_ADMIN' | 'OPERATIONS_SPECIALIST' | 'PLATFORM_DASHBOARD';
    status: 'PENDING_ACTIVATION' | 'ACTIVE' | 'SUSPENDED';
    /**
     * 仅本次响应展示，由超管安全交付给账号本人
     */
    readonly initialPassword: string;
};

export type AdministrativeDivisionDto = {
    code: string;
    name: string;
    level: 'PROVINCE' | 'PREFECTURE';
    parentCode: string | null;
};

export type CurrentOrganizationDto = {
    id: string;
    type: 'PLATFORM' | 'UNIVERSITY' | 'ENTERPRISE' | 'GOVERNMENT';
    name: string;
    status: 'ACTIVE' | 'DISABLED';
};

export type InitialTenantAdminDto = {
    displayName: string;
    /**
     * 用户端管理员手机号；租户管理员不是平台管理账号
     */
    phone: string;
};

export type CreateUniversityDto = {
    name: string;
    initialAdmin: InitialTenantAdminDto;
};

export type CreatedTenantDto = {
    tenantId: string;
    type: 'UNIVERSITY' | 'ENTERPRISE' | 'GOVERNMENT';
    name: string;
    initialAdminAccountId: string;
};

export type CreatedUniversityAdminDto = {
    accountId: string;
};

export type CreateEnterpriseDto = {
    name: string;
    initialAdmin: InitialTenantAdminDto;
    natureTagCode: string;
    industryCategoryCode: string;
    /**
     * 至少一个受控地级市行政区划代码
     */
    locationCodes: Array<string>;
};

export type CreateGovernmentDto = {
    name: string;
    initialAdmin: InitialTenantAdminDto;
    divisionCode: string;
    /**
     * 政务端允许聚合查看的高校租户白名单
     */
    visibleUniversityTenantIds: Array<string>;
};

export type CampusDto = {
    id: string;
    name: string;
    divisionCode: string;
    status: 'ACTIVE' | 'DISABLED';
};

export type CollegeCampusLinkDto = {
    campusId: string;
    sortOrder: number;
};

export type OrgTreeClassDto = {
    id: string;
    name: string;
    gradeLabel: string;
    counselorMembershipId: string | null;
    status: 'ACTIVE' | 'DISABLED';
};

export type OrgTreeMajorDto = {
    id: string;
    name: string;
    status: 'ACTIVE' | 'DISABLED';
    classes: Array<OrgTreeClassDto>;
};

export type OrgTreeCollegeDto = {
    id: string;
    name: string;
    status: 'ACTIVE' | 'DISABLED';
    campuses: Array<CollegeCampusLinkDto>;
    majors: Array<OrgTreeMajorDto>;
};

export type UniversityMemberDto = {
    accountId: string;
    membershipId: string;
    displayName: string;
    phone: string | null;
    role: 'UNIVERSITY_ADMIN' | 'UNIVERSITY_DASHBOARD' | 'COLLEGE_ADMIN' | 'PROGRAM_LEAD' | 'COUNSELOR';
    collegeId: string | null;
    accountStatus: 'PENDING_ACTIVATION' | 'ACTIVE' | 'SUSPENDED';
    membershipStatus: 'ACTIVE' | 'DISABLED';
};

export type UniversityOrgTreeDto = {
    campuses: Array<CampusDto>;
    colleges: Array<OrgTreeCollegeDto>;
    members: Array<UniversityMemberDto>;
};

export type CreateCampusDto = {
    name: string;
    /**
     * 地级市行政区划代码
     */
    divisionCode: string;
};

export type CreateCollegeDto = {
    name: string;
    /**
     * 至少一个本校校区，顺序即学院校区排序
     */
    campusIds: Array<string>;
};

export type CollegeSummaryDto = {
    id: string;
    name: string;
    status: 'ACTIVE' | 'DISABLED';
};

export type ReplaceCollegeCampusesDto = {
    campusIds: Array<string>;
};

export type CreateMajorDto = {
    collegeId: string;
    name: string;
};

export type MajorSummaryDto = {
    id: string;
    collegeId: string;
    name: string;
    status: 'ACTIVE' | 'DISABLED';
};

export type CreateClassDto = {
    majorId: string;
    name: string;
    gradeLabel: string;
    counselorMembershipId?: string;
};

export type ClassSummaryDto = {
    id: string;
    majorId: string;
    name: string;
    gradeLabel: string;
    counselorMembershipId: string | null;
    status: 'ACTIVE' | 'DISABLED';
};

export type AssignClassCounselorDto = {
    counselorMembershipId: string | null;
};

export type CreateUniversityMemberDto = {
    displayName: string;
    phone: string;
    role: 'UNIVERSITY_DASHBOARD' | 'COLLEGE_ADMIN' | 'PROGRAM_LEAD' | 'COUNSELOR';
    /**
     * 院管 / 专业负责人 / 辅导员必填
     */
    collegeId?: string;
};

export type ImportClassStudentsDto = {
    /**
     * UTF-8 CSV 全文（原始文件只在请求内解析，不落对象存储）。表头必须为「姓名,学号,手机号,性别」，字段一律必填；性别只接受男 / 女；单次至多 2000 行。班级由路径参数绑定，CSV 无班级字段。
     */
    csv: string;
};

export type PhoneOccupationDto = {
    subjectType: 'PLATFORM_STUDENT' | 'UNIVERSITY_STUDENT_CURRENT_TENANT' | 'UNIVERSITY_STUDENT_OTHER_TENANT' | 'UNIVERSITY_STAFF' | 'ENTERPRISE_MEMBER' | 'GOVERNMENT_ACCOUNT' | 'UNKNOWN';
    /**
     * 占用该手机号的主体所在租户名称（可识别学校 / 企业）
     */
    tenantName: string | null;
    /**
     * 占用者为高校认证学员时的学号（本校占用时用于核对名册）
     */
    studentNumber: string | null;
    /**
     * 处理指引（如：该号已注册为平台学员，请学生先自助注销后重导）
     */
    guidance: string;
};

export type StudentImportFailureDto = {
    /**
     * 物理记录行号（含表头，从 2 起）
     */
    row: number;
    name: string | null;
    studentNumber: string | null;
    phone: string | null;
    reason: 'INVALID_ROW' | 'INVALID_NAME' | 'INVALID_STUDENT_NUMBER' | 'INVALID_PHONE' | 'INVALID_GENDER' | 'DUPLICATE_STUDENT_NUMBER_IN_FILE' | 'DUPLICATE_PHONE_IN_FILE' | 'PHONE_ALREADY_USED' | 'STUDENT_NUMBER_ALREADY_USED';
    /**
     * 失败原因说明（面向辅导员的中文文案）
     */
    detail: string;
    /**
     * 仅 PHONE_ALREADY_USED 提供：手机号占用主体类型与处理指引
     */
    occupation?: PhoneOccupationDto;
};

export type StudentImportResultDto = {
    /**
     * 成功导入并创建的学生数（其余失败行见 failures）
     */
    createdCount: number;
    failures: Array<StudentImportFailureDto>;
};

export type ConfirmUserActivationDtoWritable = {
    phone: string;
    code: string;
    password: string;
    /**
     * 当前用户协议与隐私政策版本 ID；首次部署未发布时为空数组
     */
    consentDocumentVersionIds: Array<string>;
};

export type ConfirmSmsLoginDtoWritable = {
    phone: string;
    code: string;
    /**
     * 账号已绑定 TOTP 时必填：六位动态码或一次性恢复码
     */
    secondFactorCode?: string;
    /**
     * 当前用户协议与隐私政策版本 ID；首次部署未发布时为空数组
     */
    consentDocumentVersionIds: Array<string>;
};

export type CreateUserPasswordSessionDtoWritable = {
    /**
     * 用户端中国大陆手机号；平台管理账号不使用本入口
     */
    phone: string;
    password: string;
    /**
     * 账号已绑定 TOTP 时必填：六位动态码或一次性恢复码
     */
    secondFactorCode?: string;
    /**
     * 当前用户协议与隐私政策版本 ID；首次部署未发布时为空数组
     */
    consentDocumentVersionIds: Array<string>;
};

export type CreatePlatformSessionDtoWritable = {
    /**
     * 平台管理账号唯一用户名；平台账号不绑定手机号
     */
    username: string;
    password: string;
    /**
     * 验证器六位动态码或一次性恢复码
     */
    secondFactorCode: string;
    /**
     * 当前用户协议与隐私政策版本 ID；首次部署未发布时为空数组
     */
    consentDocumentVersionIds: Array<string>;
};

export type StartPlatformEnrollmentDtoWritable = {
    username: string;
    initialPassword: string;
};

export type FinishPlatformEnrollmentDtoWritable = {
    recoveryCodesConfirmationToken: string;
    /**
     * 必须明确确认恢复码已离线保存，方可激活并签发会话
     */
    recoveryCodesSaved: true;
    /**
     * 当前用户协议与隐私政策版本 ID；首次部署未发布时为空数组
     */
    consentDocumentVersionIds: Array<string>;
};

export type CreatedPlatformAccountDtoWritable = {
    accountId: string;
    username: string;
    displayName: string;
    role: 'ORGANIZATION_ADMIN' | 'OPERATIONS_SPECIALIST' | 'PLATFORM_DASHBOARD';
    status: 'PENDING_ACTIVATION' | 'ACTIVE' | 'SUSPENDED';
};

export type HealthControllerLiveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health/live';
};

export type HealthControllerLiveResponses = {
    200: unknown;
};

export type HealthControllerReadyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health/ready';
};

export type HealthControllerReadyResponses = {
    200: unknown;
};

export type LegalDocumentGovernanceControllerListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/governance/legal-documents';
};

export type LegalDocumentGovernanceControllerListResponses = {
    200: Array<LegalDocumentDraftDto>;
};

export type LegalDocumentGovernanceControllerListResponse = LegalDocumentGovernanceControllerListResponses[keyof LegalDocumentGovernanceControllerListResponses];

export type LegalDocumentGovernanceControllerCreateData = {
    body: SaveLegalDocumentDraftDto;
    headers: {
        'x-csrf-token': string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/governance/legal-documents';
};

export type LegalDocumentGovernanceControllerCreateResponses = {
    201: LegalDocumentDraftDto;
};

export type LegalDocumentGovernanceControllerCreateResponse = LegalDocumentGovernanceControllerCreateResponses[keyof LegalDocumentGovernanceControllerCreateResponses];

export type LegalDocumentGovernanceControllerUpdateData = {
    body: SaveLegalDocumentDraftDto;
    headers: {
        'x-csrf-token': string;
    };
    path: {
        id: unknown;
    };
    query?: never;
    url: '/api/v1/governance/legal-documents/{id}';
};

export type LegalDocumentGovernanceControllerUpdateResponses = {
    200: LegalDocumentDraftDto;
};

export type LegalDocumentGovernanceControllerUpdateResponse = LegalDocumentGovernanceControllerUpdateResponses[keyof LegalDocumentGovernanceControllerUpdateResponses];

export type LegalDocumentGovernanceControllerPublishSetData = {
    body: PublishLegalDocumentSetDto;
    headers: {
        'x-csrf-token': string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/governance/legal-documents/publish-set';
};

export type LegalDocumentGovernanceControllerPublishSetResponses = {
    204: void;
};

export type LegalDocumentGovernanceControllerPublishSetResponse = LegalDocumentGovernanceControllerPublishSetResponses[keyof LegalDocumentGovernanceControllerPublishSetResponses];

export type AccountSecurityControllerStartTotpEnrollmentData = {
    body: StartTotpEnrollmentDto;
    headers: {
        'x-csrf-token': string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/account/security/totp/enrollments';
};

export type AccountSecurityControllerStartTotpEnrollmentResponses = {
    201: StartedTotpEnrollmentDto;
};

export type AccountSecurityControllerStartTotpEnrollmentResponse = AccountSecurityControllerStartTotpEnrollmentResponses[keyof AccountSecurityControllerStartTotpEnrollmentResponses];

export type AccountSecurityControllerConfirmTotpEnrollmentData = {
    body: ConfirmTotpEnrollmentDto;
    headers: {
        'x-csrf-token': string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/account/security/totp/enrollments/confirm';
};

export type AccountSecurityControllerConfirmTotpEnrollmentResponses = {
    201: RecoveryCodesDto;
};

export type AccountSecurityControllerConfirmTotpEnrollmentResponse = AccountSecurityControllerConfirmTotpEnrollmentResponses[keyof AccountSecurityControllerConfirmTotpEnrollmentResponses];

export type AccountSecurityControllerChangePasswordData = {
    body: ChangePasswordDto;
    headers: {
        'x-csrf-token': string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/account/security/password';
};

export type AccountSecurityControllerChangePasswordResponses = {
    204: void;
};

export type AccountSecurityControllerChangePasswordResponse = AccountSecurityControllerChangePasswordResponses[keyof AccountSecurityControllerChangePasswordResponses];

export type AccountSecurityControllerDisableTotpData = {
    body: DisableTotpDto;
    headers: {
        'x-csrf-token': string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/account/security/totp/disable';
};

export type AccountSecurityControllerDisableTotpResponses = {
    204: void;
};

export type AccountSecurityControllerDisableTotpResponse = AccountSecurityControllerDisableTotpResponses[keyof AccountSecurityControllerDisableTotpResponses];

export type IdentityControllerCurrentLegalDocumentsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/legal-documents/current';
};

export type IdentityControllerCurrentLegalDocumentsResponses = {
    200: Array<CurrentLegalDocumentDto>;
};

export type IdentityControllerCurrentLegalDocumentsResponse = IdentityControllerCurrentLegalDocumentsResponses[keyof IdentityControllerCurrentLegalDocumentsResponses];

export type IdentityControllerIssueCaptchaChallengeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/captcha/challenges';
};

export type IdentityControllerIssueCaptchaChallengeResponses = {
    201: CaptchaChallengeDto;
};

export type IdentityControllerIssueCaptchaChallengeResponse = IdentityControllerIssueCaptchaChallengeResponses[keyof IdentityControllerIssueCaptchaChallengeResponses];

export type IdentityControllerRequestUserActivationCodeData = {
    body: RequestUserActivationCodeDto;
    path?: never;
    query?: never;
    url: '/api/v1/auth/user/activation/codes';
};

export type IdentityControllerRequestUserActivationCodeResponses = {
    201: ActivationCodeDeliveryDto;
};

export type IdentityControllerRequestUserActivationCodeResponse = IdentityControllerRequestUserActivationCodeResponses[keyof IdentityControllerRequestUserActivationCodeResponses];

export type IdentityControllerConfirmUserActivationData = {
    body: ConfirmUserActivationDtoWritable;
    path?: never;
    query?: never;
    url: '/api/v1/auth/user/activation/confirm';
};

export type IdentityControllerConfirmUserActivationResponses = {
    201: CreatedSessionDto;
};

export type IdentityControllerConfirmUserActivationResponse = IdentityControllerConfirmUserActivationResponses[keyof IdentityControllerConfirmUserActivationResponses];

export type IdentityControllerRequestSmsLoginCodeData = {
    body: RequestSmsLoginCodeDto;
    path?: never;
    query?: never;
    url: '/api/v1/auth/user/sms-login/codes';
};

export type IdentityControllerRequestSmsLoginCodeResponses = {
    201: SmsLoginCodeDeliveryDto;
};

export type IdentityControllerRequestSmsLoginCodeResponse = IdentityControllerRequestSmsLoginCodeResponses[keyof IdentityControllerRequestSmsLoginCodeResponses];

export type IdentityControllerConfirmSmsLoginData = {
    body: ConfirmSmsLoginDtoWritable;
    path?: never;
    query?: never;
    url: '/api/v1/auth/user/sms-login/confirm';
};

export type IdentityControllerConfirmSmsLoginResponses = {
    201: CreatedSessionDto;
};

export type IdentityControllerConfirmSmsLoginResponse = IdentityControllerConfirmSmsLoginResponses[keyof IdentityControllerConfirmSmsLoginResponses];

export type IdentityControllerCreateUserPasswordSessionData = {
    body: CreateUserPasswordSessionDtoWritable;
    path?: never;
    query?: never;
    url: '/api/v1/auth/sessions';
};

export type IdentityControllerCreateUserPasswordSessionResponses = {
    201: CreatedSessionDto;
};

export type IdentityControllerCreateUserPasswordSessionResponse = IdentityControllerCreateUserPasswordSessionResponses[keyof IdentityControllerCreateUserPasswordSessionResponses];

export type IdentityControllerCreatePlatformSessionData = {
    body: CreatePlatformSessionDtoWritable;
    path?: never;
    query?: never;
    url: '/api/v1/auth/platform/sessions';
};

export type IdentityControllerCreatePlatformSessionResponses = {
    201: CreatedSessionDto;
};

export type IdentityControllerCreatePlatformSessionResponse = IdentityControllerCreatePlatformSessionResponses[keyof IdentityControllerCreatePlatformSessionResponses];

export type IdentityControllerStartPlatformEnrollmentData = {
    body: StartPlatformEnrollmentDtoWritable;
    path?: never;
    query?: never;
    url: '/api/v1/auth/platform/enrollments';
};

export type IdentityControllerStartPlatformEnrollmentResponses = {
    201: StartedPlatformEnrollmentDto;
};

export type IdentityControllerStartPlatformEnrollmentResponse = IdentityControllerStartPlatformEnrollmentResponses[keyof IdentityControllerStartPlatformEnrollmentResponses];

export type IdentityControllerConfirmPlatformEnrollmentData = {
    body: ConfirmPlatformEnrollmentDto;
    path?: never;
    query?: never;
    url: '/api/v1/auth/platform/enrollments/confirm';
};

export type IdentityControllerConfirmPlatformEnrollmentResponses = {
    201: ConfirmedPlatformEnrollmentDto;
};

export type IdentityControllerConfirmPlatformEnrollmentResponse = IdentityControllerConfirmPlatformEnrollmentResponses[keyof IdentityControllerConfirmPlatformEnrollmentResponses];

export type IdentityControllerFinishPlatformEnrollmentData = {
    body: FinishPlatformEnrollmentDtoWritable;
    path?: never;
    query?: never;
    url: '/api/v1/auth/platform/enrollments/finish';
};

export type IdentityControllerFinishPlatformEnrollmentResponses = {
    201: CreatedSessionDto;
};

export type IdentityControllerFinishPlatformEnrollmentResponse = IdentityControllerFinishPlatformEnrollmentResponses[keyof IdentityControllerFinishPlatformEnrollmentResponses];

export type IdentityControllerRevokeCurrentSessionData = {
    body?: never;
    headers: {
        'x-csrf-token': string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/auth/sessions/current';
};

export type IdentityControllerRevokeCurrentSessionResponses = {
    204: void;
};

export type IdentityControllerRevokeCurrentSessionResponse = IdentityControllerRevokeCurrentSessionResponses[keyof IdentityControllerRevokeCurrentSessionResponses];

export type IdentityControllerCurrentSessionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/sessions/current';
};

export type IdentityControllerCurrentSessionResponses = {
    200: SessionAccountDto;
};

export type IdentityControllerCurrentSessionResponse = IdentityControllerCurrentSessionResponses[keyof IdentityControllerCurrentSessionResponses];

export type PlatformAccountControllerCreateData = {
    body: CreatePlatformAccountDto;
    headers: {
        'x-csrf-token': string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/platform/accounts';
};

export type PlatformAccountControllerCreateResponses = {
    201: CreatedPlatformAccountDto;
};

export type PlatformAccountControllerCreateResponse = PlatformAccountControllerCreateResponses[keyof PlatformAccountControllerCreateResponses];

export type PlatformAccountControllerDisableData = {
    body?: never;
    headers: {
        'x-csrf-token': string;
    };
    path: {
        accountId: unknown;
    };
    query?: never;
    url: '/api/v1/platform/accounts/{accountId}/disable';
};

export type PlatformAccountControllerDisableResponses = {
    204: void;
};

export type PlatformAccountControllerDisableResponse = PlatformAccountControllerDisableResponses[keyof PlatformAccountControllerDisableResponses];

export type PlatformAccountControllerResetTotpData = {
    body?: never;
    headers: {
        'x-csrf-token': string;
    };
    path: {
        accountId: unknown;
    };
    query?: never;
    url: '/api/v1/platform/accounts/{accountId}/totp-reset';
};

export type PlatformAccountControllerResetTotpResponses = {
    204: void;
};

export type PlatformAccountControllerResetTotpResponse = PlatformAccountControllerResetTotpResponses[keyof PlatformAccountControllerResetTotpResponses];

export type StudentSecurityControllerDisableStudentTotpData = {
    body?: never;
    headers: {
        'x-csrf-token': string;
    };
    path: {
        accountId: unknown;
    };
    query?: never;
    url: '/api/v1/university/students/{accountId}/totp-disable';
};

export type StudentSecurityControllerDisableStudentTotpResponses = {
    204: void;
};

export type StudentSecurityControllerDisableStudentTotpResponse = StudentSecurityControllerDisableStudentTotpResponses[keyof StudentSecurityControllerDisableStudentTotpResponses];

export type OrganizationControllerAdministrativeDivisionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/organizations/administrative-divisions';
};

export type OrganizationControllerAdministrativeDivisionsResponses = {
    200: Array<AdministrativeDivisionDto>;
};

export type OrganizationControllerAdministrativeDivisionsResponse = OrganizationControllerAdministrativeDivisionsResponses[keyof OrganizationControllerAdministrativeDivisionsResponses];

export type OrganizationControllerCurrentData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/organizations/current';
};

export type OrganizationControllerCurrentResponses = {
    200: CurrentOrganizationDto;
};

export type OrganizationControllerCurrentResponse = OrganizationControllerCurrentResponses[keyof OrganizationControllerCurrentResponses];

export type OrganizationControllerCreateUniversityData = {
    body: CreateUniversityDto;
    headers: {
        'x-csrf-token': string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/organizations/universities';
};

export type OrganizationControllerCreateUniversityResponses = {
    201: CreatedTenantDto;
};

export type OrganizationControllerCreateUniversityResponse = OrganizationControllerCreateUniversityResponses[keyof OrganizationControllerCreateUniversityResponses];

export type OrganizationControllerAddUniversityAdminData = {
    body: InitialTenantAdminDto;
    headers: {
        'x-csrf-token': string;
    };
    path: {
        tenantId: unknown;
    };
    query?: never;
    url: '/api/v1/organizations/universities/{tenantId}/admins';
};

export type OrganizationControllerAddUniversityAdminResponses = {
    201: CreatedUniversityAdminDto;
};

export type OrganizationControllerAddUniversityAdminResponse = OrganizationControllerAddUniversityAdminResponses[keyof OrganizationControllerAddUniversityAdminResponses];

export type OrganizationControllerCreateEnterpriseData = {
    body: CreateEnterpriseDto;
    headers: {
        'x-csrf-token': string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/organizations/enterprises';
};

export type OrganizationControllerCreateEnterpriseResponses = {
    201: CreatedTenantDto;
};

export type OrganizationControllerCreateEnterpriseResponse = OrganizationControllerCreateEnterpriseResponses[keyof OrganizationControllerCreateEnterpriseResponses];

export type OrganizationControllerCreateGovernmentData = {
    body: CreateGovernmentDto;
    headers: {
        'x-csrf-token': string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/organizations/governments';
};

export type OrganizationControllerCreateGovernmentResponses = {
    201: CreatedTenantDto;
};

export type OrganizationControllerCreateGovernmentResponse = OrganizationControllerCreateGovernmentResponses[keyof OrganizationControllerCreateGovernmentResponses];

export type UniversityOrganizationControllerOrgTreeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/university/org-tree';
};

export type UniversityOrganizationControllerOrgTreeResponses = {
    200: UniversityOrgTreeDto;
};

export type UniversityOrganizationControllerOrgTreeResponse = UniversityOrganizationControllerOrgTreeResponses[keyof UniversityOrganizationControllerOrgTreeResponses];

export type UniversityOrganizationControllerCreateCampusData = {
    body: CreateCampusDto;
    headers: {
        'x-csrf-token': string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/university/campuses';
};

export type UniversityOrganizationControllerCreateCampusResponses = {
    201: CampusDto;
};

export type UniversityOrganizationControllerCreateCampusResponse = UniversityOrganizationControllerCreateCampusResponses[keyof UniversityOrganizationControllerCreateCampusResponses];

export type UniversityOrganizationControllerCreateCollegeData = {
    body: CreateCollegeDto;
    headers: {
        'x-csrf-token': string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/university/colleges';
};

export type UniversityOrganizationControllerCreateCollegeResponses = {
    201: CollegeSummaryDto;
};

export type UniversityOrganizationControllerCreateCollegeResponse = UniversityOrganizationControllerCreateCollegeResponses[keyof UniversityOrganizationControllerCreateCollegeResponses];

export type UniversityOrganizationControllerReplaceCollegeCampusesData = {
    body: ReplaceCollegeCampusesDto;
    headers: {
        'x-csrf-token': string;
    };
    path: {
        collegeId: unknown;
    };
    query?: never;
    url: '/api/v1/university/colleges/{collegeId}/campuses';
};

export type UniversityOrganizationControllerReplaceCollegeCampusesResponses = {
    204: void;
};

export type UniversityOrganizationControllerReplaceCollegeCampusesResponse = UniversityOrganizationControllerReplaceCollegeCampusesResponses[keyof UniversityOrganizationControllerReplaceCollegeCampusesResponses];

export type UniversityOrganizationControllerCreateMajorData = {
    body: CreateMajorDto;
    headers: {
        'x-csrf-token': string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/university/majors';
};

export type UniversityOrganizationControllerCreateMajorResponses = {
    201: MajorSummaryDto;
};

export type UniversityOrganizationControllerCreateMajorResponse = UniversityOrganizationControllerCreateMajorResponses[keyof UniversityOrganizationControllerCreateMajorResponses];

export type UniversityOrganizationControllerCreateClassData = {
    body: CreateClassDto;
    headers: {
        'x-csrf-token': string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/university/classes';
};

export type UniversityOrganizationControllerCreateClassResponses = {
    201: ClassSummaryDto;
};

export type UniversityOrganizationControllerCreateClassResponse = UniversityOrganizationControllerCreateClassResponses[keyof UniversityOrganizationControllerCreateClassResponses];

export type UniversityOrganizationControllerAssignClassCounselorData = {
    body: AssignClassCounselorDto;
    headers: {
        'x-csrf-token': string;
    };
    path: {
        classId: unknown;
    };
    query?: never;
    url: '/api/v1/university/classes/{classId}/counselor';
};

export type UniversityOrganizationControllerAssignClassCounselorResponses = {
    200: ClassSummaryDto;
};

export type UniversityOrganizationControllerAssignClassCounselorResponse = UniversityOrganizationControllerAssignClassCounselorResponses[keyof UniversityOrganizationControllerAssignClassCounselorResponses];

export type UniversityOrganizationControllerCreateMemberData = {
    body: CreateUniversityMemberDto;
    headers: {
        'x-csrf-token': string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/university/members';
};

export type UniversityOrganizationControllerCreateMemberResponses = {
    201: UniversityMemberDto;
};

export type UniversityOrganizationControllerCreateMemberResponse = UniversityOrganizationControllerCreateMemberResponses[keyof UniversityOrganizationControllerCreateMemberResponses];

export type CounselorStudentImportControllerImportStudentsData = {
    body: ImportClassStudentsDto;
    headers: {
        'x-csrf-token': string;
    };
    path: {
        classId: unknown;
    };
    query?: never;
    url: '/api/v1/university/classes/{classId}/students/import';
};

export type CounselorStudentImportControllerImportStudentsResponses = {
    201: StudentImportResultDto;
};

export type CounselorStudentImportControllerImportStudentsResponse = CounselorStudentImportControllerImportStudentsResponses[keyof CounselorStudentImportControllerImportStudentsResponses];
