// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

export type LegalDocumentDraftDto = {
    id: string;
    type: 'USER_AGREEMENT' | 'PRIVACY_POLICY';
    version: string;
    status: 'DRAFT' | 'PUBLISHED' | 'RETIRED';
    content: string;
    contentHash: string;
    publishedAt: string | null;
    createdAt: string;
    updatedAt: string;
};

export type SaveLegalDocumentDraftDto = {
    type: 'USER_AGREEMENT' | 'PRIVACY_POLICY';
    version: string;
    content: string;
};

export type PublishLegalDocumentSetDto = {
    userAgreementDraftId: string;
    privacyPolicyDraftId: string;
};

export type StartTotpEnrollmentDto = {
    password: string;
};

export type StartedTotpEnrollmentDto = {
    secret: string;
    uri: string;
};

export type ConfirmTotpEnrollmentDto = {
    totpCode: string;
};

export type RecoveryCodesDto = {
    recoveryCodes: Array<string>;
};

export type ChangePasswordDto = {
    currentPassword: string;
    newPassword: string;
    /**
     * 已启用 TOTP 时必填
     */
    secondFactorCode?: string;
};

export type DisableTotpDto = {
    password: string;
    secondFactorCode: string;
};

export type PendingPhoneChangeDto = {
    requestId: string;
    studentAccountId: string;
    studentNumber: string;
    displayName: string;
    currentPhone: string | null;
    newPhone: string;
    createdAt: string;
    /**
     * 展示用逾期天数（不自动通过、无时限，《07》5.6）
     */
    pendingDays: number;
};

export type CounselorInitiatePhoneChangeDto = {
    newPhone: string;
    captchaToken: string;
};

export type ActivationCodeDeliveryDto = {
    messageId: string;
    mock: boolean;
    /**
     * 仅 Mock 环境返回，正式短信适配器不包含此字段
     */
    debugCode?: string;
};

export type CounselorVerifyPhoneChangeDto = {
    code: string;
};

export type CounselorResolvePhoneChangeDto = {
    approve: boolean;
};

export type CurrentLegalDocumentDto = {
    id: string;
    type: 'USER_AGREEMENT' | 'PRIVACY_POLICY';
    version: string;
    content: string;
    contentHash: string;
    publishedAt: string;
};

export type CaptchaChallengeDto = {
    token: string;
    mock: boolean;
};

export type RequestUserActivationCodeDto = {
    phone: string;
    captchaToken: string;
};

export type ConfirmUserActivationDto = {
    phone: string;
    /**
     * 当前用户协议与隐私政策版本 ID；首次部署未发布时为空数组
     */
    consentDocumentVersionIds: Array<string>;
};

export type SessionAccountDto = {
    accountId: string;
    displayName: string;
    kind: 'PLATFORM_ADMIN' | 'END_USER';
    tenantId: string;
    role: 'SUPER_ADMIN' | 'ORGANIZATION_ADMIN' | 'OPERATIONS_SPECIALIST' | 'PLATFORM_DASHBOARD' | 'UNIVERSITY_ADMIN' | 'COLLEGE_ADMIN' | 'PROGRAM_LEAD' | 'COUNSELOR' | 'STUDENT' | 'UNIVERSITY_DASHBOARD' | 'ENTERPRISE_ADMIN' | 'HR' | 'PROJECT_LEAD' | 'MENTOR' | 'ENTERPRISE_DASHBOARD' | 'GOVERNMENT_DASHBOARD_ADMIN' | 'GOVERNMENT_DASHBOARD';
};

export type CreatedSessionDto = {
    /**
     * 用于同源写请求的 CSRF 双提交令牌
     */
    csrfToken: string;
    expiresAt: string;
    account: SessionAccountDto;
};

export type RequestSmsLoginCodeDto = {
    phone: string;
    captchaToken: string;
};

export type SmsLoginCodeDeliveryDto = {
    messageId: string;
    mock: boolean;
    /**
     * 仅 Mock 环境返回，正式短信适配器不包含此字段
     */
    debugCode?: string;
    /**
     * 该账号已绑定 TOTP，确认短信码时还须提交第二因子
     */
    secondFactorRequired: boolean;
};

export type ConfirmSmsLoginDto = {
    phone: string;
    /**
     * 当前用户协议与隐私政策版本 ID；首次部署未发布时为空数组
     */
    consentDocumentVersionIds: Array<string>;
};

export type CreateUserPasswordSessionDto = {
    /**
     * 用户端中国大陆手机号；平台管理账号不使用本入口
     */
    phone: string;
    /**
     * 当前用户协议与隐私政策版本 ID；首次部署未发布时为空数组
     */
    consentDocumentVersionIds: Array<string>;
};

export type CreatePlatformSessionDto = {
    /**
     * 平台管理账号唯一用户名；平台账号不绑定手机号
     */
    username: string;
    /**
     * 当前用户协议与隐私政策版本 ID；首次部署未发布时为空数组
     */
    consentDocumentVersionIds: Array<string>;
};

export type StartPlatformEnrollmentDto = {
    username: string;
};

export type StartedPlatformEnrollmentDto = {
    enrollmentToken: string;
    /**
     * 仅本次响应展示，供无法扫码时手工录入验证器
     */
    totpSecret: string;
    /**
     * 供验证器扫码或导入的 otpauth URI
     */
    totpUri: string;
    expiresAt: string;
};

export type ConfirmPlatformEnrollmentDto = {
    enrollmentToken: string;
    newPassword: string;
    totpCode: string;
};

export type ConfirmedPlatformEnrollmentDto = {
    /**
     * 确认恢复码已保存时使用的一次性短效令牌
     */
    recoveryCodesConfirmationToken: string;
    expiresAt: string;
    /**
     * 仅本次响应展示，须立即离线保存
     */
    recoveryCodes: Array<string>;
};

export type FinishPlatformEnrollmentDto = {
    /**
     * 必须明确确认恢复码已离线保存，方可激活并签发会话
     */
    recoveryCodesSaved: true;
    /**
     * 当前用户协议与隐私政策版本 ID；首次部署未发布时为空数组
     */
    consentDocumentVersionIds: Array<string>;
};

export type RequestPhoneChangeOldCodeDto = {
    captchaToken: string;
};

export type RequestPhoneChangeNewCodeDto = {
    oldPhoneCode: string;
    newPhone: string;
    captchaToken: string;
};

export type ConfirmPhoneChangeDto = {
    newPhoneCode: string;
};

export type PhoneChangeConfirmResultDto = {
    applied: boolean;
    /**
     * 高校认证学员换绑须辅导员确认后生效（《07》5.6）
     */
    requiresCounselorConfirmation: boolean;
};

export type CreatePlatformAccountDto = {
    username: string;
    displayName: string;
    role: 'ORGANIZATION_ADMIN' | 'OPERATIONS_SPECIALIST' | 'PLATFORM_DASHBOARD';
};

export type CreatedPlatformAccountDto = {
    accountId: string;
    username: string;
    displayName: string;
    role: 'ORGANIZATION_ADMIN' | 'OPERATIONS_SPECIALIST' | 'PLATFORM_DASHBOARD';
    status: 'PENDING_ACTIVATION' | 'ACTIVE' | 'SUSPENDED';
    /**
     * 仅本次响应展示，由超管安全交付给账号本人
     */
    readonly initialPassword: string;
};

export type RequestRegistrationCodeDto = {
    phone: string;
    captchaToken: string;
};

export type ConfirmRegistrationDto = {
    phone: string;
    code: string;
    consentDocumentVersionIds: Array<string>;
    displayName: string;
    /**
     * 平台学员注册可选：男 / 女 / 未说明
     */
    gender: 'MALE' | 'FEMALE' | 'UNSPECIFIED';
    /**
     * 出生日期，YYYY-MM-DD
     */
    birthDate: string;
    /**
     * 注册城市（地级市行政区划代码，决定归属的公开学院校区学院）
     */
    registrationCityCode: string;
};

export type StudentProfileStudentDto = {
    kind: 'UNIVERSITY_CERTIFIED' | 'PLATFORM';
    lifecycleState: 'ENROLLED' | 'GRADUATE_ACTIVE' | 'READ_ONLY' | 'SUSPENDED';
    registrationCityCode: string | null;
    residentCityCode: string | null;
    /**
     * 注册信息冻结截止（平台学员自注册起 90 天）
     */
    profileFrozenUntil: string | null;
    /**
     * 最近一次自助修改（滚动 365 天至多 1 次的基准）
     */
    lastSelfEditedAt: string | null;
};

export type MyProfileDto = {
    accountId: string;
    displayName: string;
    gender: 'MALE' | 'FEMALE' | 'UNSPECIFIED';
    birthDate: string | null;
    politicalAffiliation: string | null;
    /**
     * 首登资料补齐完成时间；为空表示业务门禁尚未放行
     */
    profileCompletedAt: string | null;
    student: StudentProfileStudentDto | null;
};

export type CompleteFirstLoginProfileDto = {
    /**
     * 出生年月日（必填），YYYY-MM-DD
     */
    birthDate: string;
    /**
     * 政治面貌（选填；平台无功能消费该字段，不作筛选条件）
     */
    politicalAffiliation?: string;
};

export type UpdateResidentCityDto = {
    residentCityCode: string;
};

export type SelfCorrectProfileDto = {
    displayName?: string;
    gender?: 'MALE' | 'FEMALE' | 'UNSPECIFIED';
    /**
     * YYYY-MM-DD
     */
    birthDate?: string;
    /**
     * 注册城市变更（同步常驻城市初值）
     */
    registrationCityCode?: string;
};

export type TenantSummaryDto = {
    tenantId: string;
    type: 'UNIVERSITY' | 'ENTERPRISE' | 'GOVERNMENT';
    name: string;
    status: 'ACTIVE' | 'DISABLED';
    isPublicAcademy: boolean | null;
    createdAt: string;
};

export type AdministrativeDivisionDto = {
    code: string;
    name: string;
    level: 'PROVINCE' | 'PREFECTURE';
    parentCode: string | null;
};

export type EnterpriseNatureTagDto = {
    code: string;
    name: string;
    sortOrder: number;
};

export type IndustryCategoryDto = {
    code: string;
    name: string;
};

export type CurrentOrganizationDto = {
    id: string;
    type: 'PLATFORM' | 'UNIVERSITY' | 'ENTERPRISE' | 'GOVERNMENT';
    name: string;
    status: 'ACTIVE' | 'DISABLED';
};

export type InitialTenantAdminDto = {
    displayName: string;
    /**
     * 用户端管理员手机号；租户管理员不是平台管理账号
     */
    phone: string;
};

export type CreateUniversityDto = {
    name: string;
    initialAdmin: InitialTenantAdminDto;
};

export type CreatedTenantDto = {
    tenantId: string;
    type: 'UNIVERSITY' | 'ENTERPRISE' | 'GOVERNMENT';
    name: string;
    initialAdminAccountId: string;
};

export type CreatedUniversityAdminDto = {
    accountId: string;
};

export type CreateEnterpriseDto = {
    name: string;
    initialAdmin: InitialTenantAdminDto;
    natureTagCode: string;
    industryCategoryCode: string;
    /**
     * 至少一个受控地级市行政区划代码
     */
    locationCodes: Array<string>;
};

export type CreateGovernmentDto = {
    name: string;
    initialAdmin: InitialTenantAdminDto;
    divisionCode: string;
    /**
     * 政务端允许聚合查看的高校租户白名单
     */
    visibleUniversityTenantIds: Array<string>;
};

export type ReplaceGovernmentScopesDto = {
    /**
     * 政务端允许聚合查看的高校租户白名单
     */
    visibleUniversityTenantIds: Array<string>;
};

export type SubmitOnboardingLeadDto = {
    kind: 'UNIVERSITY' | 'ENTERPRISE';
    institutionName: string;
    contactName: string;
    /**
     * 联系方式（电话 / 邮箱等）
     */
    contactMethod: string;
    intent: string;
    captchaToken: string;
};

export type OnboardingLeadDto = {
    id: string;
    kind: 'UNIVERSITY' | 'ENTERPRISE';
    institutionName: string;
    contactName: string;
    contactMethod: string;
    intent: string;
    status: 'NEW' | 'IN_PROGRESS' | 'OPENED' | 'CLOSED';
    createdAt: string;
    statusChangedAt: string | null;
};

export type UpdateOnboardingLeadStatusDto = {
    status: 'NEW' | 'IN_PROGRESS' | 'OPENED' | 'CLOSED';
};

export type CampusDto = {
    id: string;
    name: string;
    divisionCode: string;
    status: 'ACTIVE' | 'DISABLED';
};

export type CollegeCampusLinkDto = {
    campusId: string;
    sortOrder: number;
};

export type OrgTreeClassDto = {
    id: string;
    name: string;
    gradeLabel: string;
    counselorMembershipId: string | null;
    status: 'ACTIVE' | 'DISABLED';
};

export type OrgTreeMajorDto = {
    id: string;
    name: string;
    status: 'ACTIVE' | 'DISABLED';
    classes: Array<OrgTreeClassDto>;
};

export type OrgTreeCollegeDto = {
    id: string;
    name: string;
    status: 'ACTIVE' | 'DISABLED';
    campuses: Array<CollegeCampusLinkDto>;
    majors: Array<OrgTreeMajorDto>;
};

export type UniversityMemberDto = {
    accountId: string;
    membershipId: string;
    displayName: string;
    phone: string | null;
    role: 'UNIVERSITY_ADMIN' | 'UNIVERSITY_DASHBOARD' | 'COLLEGE_ADMIN' | 'PROGRAM_LEAD' | 'COUNSELOR';
    collegeId: string | null;
    accountStatus: 'PENDING_ACTIVATION' | 'ACTIVE' | 'SUSPENDED';
    membershipStatus: 'ACTIVE' | 'DISABLED';
};

export type UniversityOrgTreeDto = {
    campuses: Array<CampusDto>;
    colleges: Array<OrgTreeCollegeDto>;
    members: Array<UniversityMemberDto>;
};

export type CreateCampusDto = {
    name: string;
    /**
     * 地级市行政区划代码
     */
    divisionCode: string;
};

export type CreateCollegeDto = {
    name: string;
    /**
     * 至少一个本校校区，顺序即学院校区排序
     */
    campusIds: Array<string>;
};

export type CollegeSummaryDto = {
    id: string;
    name: string;
    status: 'ACTIVE' | 'DISABLED';
};

export type ReplaceCollegeCampusesDto = {
    campusIds: Array<string>;
};

export type CreateMajorDto = {
    collegeId: string;
    name: string;
};

export type MajorSummaryDto = {
    id: string;
    collegeId: string;
    name: string;
    status: 'ACTIVE' | 'DISABLED';
};

export type CreateClassDto = {
    majorId: string;
    name: string;
    gradeLabel: string;
    counselorMembershipId?: string;
};

export type ClassSummaryDto = {
    id: string;
    majorId: string;
    name: string;
    gradeLabel: string;
    counselorMembershipId: string | null;
    status: 'ACTIVE' | 'DISABLED';
};

export type AssignClassCounselorDto = {
    counselorMembershipId: string | null;
};

export type CreateUniversityMemberDto = {
    displayName: string;
    phone: string;
    role: 'UNIVERSITY_DASHBOARD' | 'COLLEGE_ADMIN' | 'PROGRAM_LEAD' | 'COUNSELOR';
    /**
     * 院管 / 专业负责人 / 辅导员必填
     */
    collegeId?: string;
};

export type HandoverUniversityMemberDto = {
    successorMembershipId: string;
};

export type StaffHandoverResultDto = {
    fromMembershipId: string;
    toMembershipId: string;
    role: 'UNIVERSITY_DASHBOARD' | 'COLLEGE_ADMIN' | 'PROGRAM_LEAD' | 'COUNSELOR';
    reassignedClassCount: number;
};

export type ClassTransferRequestDto = {
    id: string;
    studentAccountId: string;
    fromClassId: string;
    toClassId: string;
    status: 'PENDING_OUTGOING' | 'PENDING_INCOMING' | 'APPROVED' | 'REJECTED';
    createdAt: string;
    outgoingResolvedAt: string | null;
    incomingResolvedAt: string | null;
    resolvedAt: string | null;
};

export type ResolveClassTransferDto = {
    approve: boolean;
};

export type CreateClassTransferDto = {
    targetClassId: string;
};

export type ImportClassStudentsDto = {
    /**
     * UTF-8 CSV 全文（原始文件只在请求内解析，不落对象存储）。表头必须为「姓名,学号,手机号,性别」，字段一律必填；性别只接受男 / 女；单次至多 2000 行。班级由路径参数绑定，CSV 无班级字段。
     */
    csv: string;
};

export type PhoneOccupationDto = {
    subjectType: 'PLATFORM_STUDENT' | 'UNIVERSITY_STUDENT_CURRENT_TENANT' | 'UNIVERSITY_STUDENT_OTHER_TENANT' | 'UNIVERSITY_STAFF' | 'ENTERPRISE_MEMBER' | 'GOVERNMENT_ACCOUNT' | 'UNKNOWN';
    /**
     * 占用该手机号的主体所在租户名称（可识别学校 / 企业）
     */
    tenantName: string | null;
    /**
     * 占用者为高校认证学员时的学号（本校占用时用于核对名册）
     */
    studentNumber: string | null;
    /**
     * 处理指引（如：该号已注册为平台学员，请学生先自助注销后重导）
     */
    guidance: string;
};

export type StudentImportFailureDto = {
    /**
     * 物理记录行号（含表头，从 2 起）
     */
    row: number;
    name: string | null;
    studentNumber: string | null;
    phone: string | null;
    reason: 'INVALID_ROW' | 'INVALID_NAME' | 'INVALID_STUDENT_NUMBER' | 'INVALID_PHONE' | 'INVALID_GENDER' | 'DUPLICATE_STUDENT_NUMBER_IN_FILE' | 'DUPLICATE_PHONE_IN_FILE' | 'PHONE_ALREADY_USED' | 'STUDENT_NUMBER_ALREADY_USED';
    /**
     * 失败原因说明（面向辅导员的中文文案）
     */
    detail: string;
    /**
     * 仅 PHONE_ALREADY_USED 提供：手机号占用主体类型与处理指引
     */
    occupation?: PhoneOccupationDto;
};

export type StudentImportResultDto = {
    /**
     * 成功导入并创建的学生数（其余失败行见 failures）
     */
    createdCount: number;
    failures: Array<StudentImportFailureDto>;
};

export type StudentSummaryDto = {
    accountId: string;
    studentNumber: string;
    displayName: string;
    gender: 'MALE' | 'FEMALE' | 'UNSPECIFIED';
    phone: string | null;
    lifecycleState: 'ENROLLED' | 'GRADUATE_ACTIVE' | 'READ_ONLY' | 'SUSPENDED';
    accountStatus: 'PENDING_ACTIVATION' | 'ACTIVE' | 'SUSPENDED';
    classId: string | null;
    /**
     * 毕业时间（毕业活跃态起算，满 2 年转纯只读态）
     */
    graduatedAt: string | null;
    createdAt: string;
};

export type CreateClassStudentDto = {
    /**
     * 姓名（学校名册为准，2–100 字符）
     */
    name: string;
    /**
     * 学号（本校终身不回收；数字、字母与连字符，1–50）
     */
    studentNumber: string;
    phone: string;
    /**
     * 性别（CSV 导入同口径：仅男 / 女）
     */
    gender: 'MALE' | 'FEMALE';
};

export type GraduateClassStudentsDto = {
    /**
     * 本班在读学生账户 ID（单个毕业即传一个）
     */
    studentIds: Array<string>;
};

export type CorrectStudentIdentityDto = {
    /**
     * 更正后的姓名（与性别至少提供一项）
     */
    displayName?: string;
    /**
     * 更正后的性别（与姓名至少提供一项）
     */
    gender?: 'MALE' | 'FEMALE';
};

export type EnterpriseLocationDto = {
    id: string;
    divisionCode: string;
};

export type EnterpriseDepartmentDto = {
    id: string;
    name: string;
    status: 'ACTIVE' | 'DISABLED';
};

export type EnterpriseMemberDto = {
    accountId: string;
    membershipId: string;
    displayName: string;
    phone: string | null;
    role: 'ENTERPRISE_ADMIN' | 'HR' | 'PROJECT_LEAD' | 'MENTOR' | 'ENTERPRISE_DASHBOARD';
    departmentId: string | null;
    accountStatus: 'PENDING_ACTIVATION' | 'ACTIVE' | 'SUSPENDED';
    membershipStatus: 'ACTIVE' | 'DISABLED';
};

export type EnterpriseOrgDto = {
    natureTagCode: string;
    industryCategoryCode: string;
    locations: Array<EnterpriseLocationDto>;
    departments: Array<EnterpriseDepartmentDto>;
    members: Array<EnterpriseMemberDto>;
};

export type CreateEnterpriseDepartmentDto = {
    name: string;
};

export type ReplaceEnterpriseLocationsDto = {
    locationCodes: Array<string>;
};

export type CreateEnterpriseMemberDto = {
    displayName: string;
    phone: string;
    role: 'HR' | 'PROJECT_LEAD' | 'MENTOR' | 'ENTERPRISE_DASHBOARD';
    departmentId: string;
};

export type GovernmentMemberDto = {
    accountId: string;
    membershipId: string;
    displayName: string;
    phone: string | null;
    role: 'GOVERNMENT_DASHBOARD_ADMIN' | 'GOVERNMENT_DASHBOARD';
    accountStatus: 'PENDING_ACTIVATION' | 'ACTIVE' | 'SUSPENDED';
    membershipStatus: 'ACTIVE' | 'DISABLED';
};

export type CreateGovernmentMemberDto = {
    displayName: string;
    phone: string;
};

export type PublicAcademyCampusDto = {
    id: string;
    name: string;
    divisionCode: string;
    status: 'ACTIVE' | 'DISABLED';
    studentCount?: number;
};

export type SetPublicAcademyCampusStatusDto = {
    status: 'ACTIVE' | 'DISABLED';
};

export type ConfirmUserActivationDtoWritable = {
    phone: string;
    code: string;
    password: string;
    /**
     * 当前用户协议与隐私政策版本 ID；首次部署未发布时为空数组
     */
    consentDocumentVersionIds: Array<string>;
};

export type ConfirmSmsLoginDtoWritable = {
    phone: string;
    code: string;
    /**
     * 账号已绑定 TOTP 时必填：六位动态码或一次性恢复码
     */
    secondFactorCode?: string;
    /**
     * 当前用户协议与隐私政策版本 ID；首次部署未发布时为空数组
     */
    consentDocumentVersionIds: Array<string>;
};

export type CreateUserPasswordSessionDtoWritable = {
    /**
     * 用户端中国大陆手机号；平台管理账号不使用本入口
     */
    phone: string;
    password: string;
    /**
     * 账号已绑定 TOTP 时必填：六位动态码或一次性恢复码
     */
    secondFactorCode?: string;
    /**
     * 当前用户协议与隐私政策版本 ID；首次部署未发布时为空数组
     */
    consentDocumentVersionIds: Array<string>;
};

export type CreatePlatformSessionDtoWritable = {
    /**
     * 平台管理账号唯一用户名；平台账号不绑定手机号
     */
    username: string;
    password: string;
    /**
     * 验证器六位动态码或一次性恢复码
     */
    secondFactorCode: string;
    /**
     * 当前用户协议与隐私政策版本 ID；首次部署未发布时为空数组
     */
    consentDocumentVersionIds: Array<string>;
};

export type StartPlatformEnrollmentDtoWritable = {
    username: string;
    initialPassword: string;
};

export type FinishPlatformEnrollmentDtoWritable = {
    recoveryCodesConfirmationToken: string;
    /**
     * 必须明确确认恢复码已离线保存，方可激活并签发会话
     */
    recoveryCodesSaved: true;
    /**
     * 当前用户协议与隐私政策版本 ID；首次部署未发布时为空数组
     */
    consentDocumentVersionIds: Array<string>;
};

export type CreatedPlatformAccountDtoWritable = {
    accountId: string;
    username: string;
    displayName: string;
    role: 'ORGANIZATION_ADMIN' | 'OPERATIONS_SPECIALIST' | 'PLATFORM_DASHBOARD';
    status: 'PENDING_ACTIVATION' | 'ACTIVE' | 'SUSPENDED';
};

export type HealthControllerLiveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health/live';
};

export type HealthControllerLiveResponses = {
    200: unknown;
};

export type HealthControllerReadyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health/ready';
};

export type HealthControllerReadyResponses = {
    200: unknown;
};

export type LegalDocumentGovernanceControllerListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/governance/legal-documents';
};

export type LegalDocumentGovernanceControllerListResponses = {
    200: Array<LegalDocumentDraftDto>;
};

export type LegalDocumentGovernanceControllerListResponse = LegalDocumentGovernanceControllerListResponses[keyof LegalDocumentGovernanceControllerListResponses];

export type LegalDocumentGovernanceControllerCreateData = {
    body: SaveLegalDocumentDraftDto;
    headers: {
        'x-csrf-token': string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/governance/legal-documents';
};

export type LegalDocumentGovernanceControllerCreateResponses = {
    201: LegalDocumentDraftDto;
};

export type LegalDocumentGovernanceControllerCreateResponse = LegalDocumentGovernanceControllerCreateResponses[keyof LegalDocumentGovernanceControllerCreateResponses];

export type LegalDocumentGovernanceControllerUpdateData = {
    body: SaveLegalDocumentDraftDto;
    headers: {
        'x-csrf-token': string;
    };
    path: {
        id: unknown;
    };
    query?: never;
    url: '/api/v1/governance/legal-documents/{id}';
};

export type LegalDocumentGovernanceControllerUpdateResponses = {
    200: LegalDocumentDraftDto;
};

export type LegalDocumentGovernanceControllerUpdateResponse = LegalDocumentGovernanceControllerUpdateResponses[keyof LegalDocumentGovernanceControllerUpdateResponses];

export type LegalDocumentGovernanceControllerPublishSetData = {
    body: PublishLegalDocumentSetDto;
    headers: {
        'x-csrf-token': string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/governance/legal-documents/publish-set';
};

export type LegalDocumentGovernanceControllerPublishSetResponses = {
    204: void;
};

export type LegalDocumentGovernanceControllerPublishSetResponse = LegalDocumentGovernanceControllerPublishSetResponses[keyof LegalDocumentGovernanceControllerPublishSetResponses];

export type AccountSecurityControllerStartTotpEnrollmentData = {
    body: StartTotpEnrollmentDto;
    headers: {
        'x-csrf-token': string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/account/security/totp/enrollments';
};

export type AccountSecurityControllerStartTotpEnrollmentResponses = {
    201: StartedTotpEnrollmentDto;
};

export type AccountSecurityControllerStartTotpEnrollmentResponse = AccountSecurityControllerStartTotpEnrollmentResponses[keyof AccountSecurityControllerStartTotpEnrollmentResponses];

export type AccountSecurityControllerConfirmTotpEnrollmentData = {
    body: ConfirmTotpEnrollmentDto;
    headers: {
        'x-csrf-token': string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/account/security/totp/enrollments/confirm';
};

export type AccountSecurityControllerConfirmTotpEnrollmentResponses = {
    201: RecoveryCodesDto;
};

export type AccountSecurityControllerConfirmTotpEnrollmentResponse = AccountSecurityControllerConfirmTotpEnrollmentResponses[keyof AccountSecurityControllerConfirmTotpEnrollmentResponses];

export type AccountSecurityControllerChangePasswordData = {
    body: ChangePasswordDto;
    headers: {
        'x-csrf-token': string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/account/security/password';
};

export type AccountSecurityControllerChangePasswordResponses = {
    204: void;
};

export type AccountSecurityControllerChangePasswordResponse = AccountSecurityControllerChangePasswordResponses[keyof AccountSecurityControllerChangePasswordResponses];

export type AccountSecurityControllerDisableTotpData = {
    body: DisableTotpDto;
    headers: {
        'x-csrf-token': string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/account/security/totp/disable';
};

export type AccountSecurityControllerDisableTotpResponses = {
    204: void;
};

export type AccountSecurityControllerDisableTotpResponse = AccountSecurityControllerDisableTotpResponses[keyof AccountSecurityControllerDisableTotpResponses];

export type CounselorPhoneChangeControllerListPendingData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/university/students/phone-change-requests';
};

export type CounselorPhoneChangeControllerListPendingResponses = {
    200: Array<PendingPhoneChangeDto>;
};

export type CounselorPhoneChangeControllerListPendingResponse = CounselorPhoneChangeControllerListPendingResponses[keyof CounselorPhoneChangeControllerListPendingResponses];

export type CounselorPhoneChangeControllerInitiateData = {
    body: CounselorInitiatePhoneChangeDto;
    headers: {
        'x-csrf-token': string;
    };
    path: {
        accountId: unknown;
    };
    query?: never;
    url: '/api/v1/university/students/{accountId}/phone-change/initiate';
};

export type CounselorPhoneChangeControllerInitiateResponses = {
    200: ActivationCodeDeliveryDto;
};

export type CounselorPhoneChangeControllerInitiateResponse = CounselorPhoneChangeControllerInitiateResponses[keyof CounselorPhoneChangeControllerInitiateResponses];

export type CounselorPhoneChangeControllerVerifyData = {
    body: CounselorVerifyPhoneChangeDto;
    headers: {
        'x-csrf-token': string;
    };
    path: {
        requestId: unknown;
    };
    query?: never;
    url: '/api/v1/university/phone-change-requests/{requestId}/verify';
};

export type CounselorPhoneChangeControllerVerifyResponses = {
    204: void;
};

export type CounselorPhoneChangeControllerVerifyResponse = CounselorPhoneChangeControllerVerifyResponses[keyof CounselorPhoneChangeControllerVerifyResponses];

export type CounselorPhoneChangeControllerResolveData = {
    body: CounselorResolvePhoneChangeDto;
    headers: {
        'x-csrf-token': string;
    };
    path: {
        requestId: unknown;
    };
    query?: never;
    url: '/api/v1/university/phone-change-requests/{requestId}/resolve';
};

export type CounselorPhoneChangeControllerResolveResponses = {
    204: void;
};

export type CounselorPhoneChangeControllerResolveResponse = CounselorPhoneChangeControllerResolveResponses[keyof CounselorPhoneChangeControllerResolveResponses];

export type IdentityControllerCurrentLegalDocumentsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/legal-documents/current';
};

export type IdentityControllerCurrentLegalDocumentsResponses = {
    200: Array<CurrentLegalDocumentDto>;
};

export type IdentityControllerCurrentLegalDocumentsResponse = IdentityControllerCurrentLegalDocumentsResponses[keyof IdentityControllerCurrentLegalDocumentsResponses];

export type IdentityControllerIssueCaptchaChallengeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/captcha/challenges';
};

export type IdentityControllerIssueCaptchaChallengeResponses = {
    201: CaptchaChallengeDto;
};

export type IdentityControllerIssueCaptchaChallengeResponse = IdentityControllerIssueCaptchaChallengeResponses[keyof IdentityControllerIssueCaptchaChallengeResponses];

export type IdentityControllerRequestUserActivationCodeData = {
    body: RequestUserActivationCodeDto;
    path?: never;
    query?: never;
    url: '/api/v1/auth/user/activation/codes';
};

export type IdentityControllerRequestUserActivationCodeResponses = {
    201: ActivationCodeDeliveryDto;
};

export type IdentityControllerRequestUserActivationCodeResponse = IdentityControllerRequestUserActivationCodeResponses[keyof IdentityControllerRequestUserActivationCodeResponses];

export type IdentityControllerConfirmUserActivationData = {
    body: ConfirmUserActivationDtoWritable;
    path?: never;
    query?: never;
    url: '/api/v1/auth/user/activation/confirm';
};

export type IdentityControllerConfirmUserActivationResponses = {
    201: CreatedSessionDto;
};

export type IdentityControllerConfirmUserActivationResponse = IdentityControllerConfirmUserActivationResponses[keyof IdentityControllerConfirmUserActivationResponses];

export type IdentityControllerRequestSmsLoginCodeData = {
    body: RequestSmsLoginCodeDto;
    path?: never;
    query?: never;
    url: '/api/v1/auth/user/sms-login/codes';
};

export type IdentityControllerRequestSmsLoginCodeResponses = {
    201: SmsLoginCodeDeliveryDto;
};

export type IdentityControllerRequestSmsLoginCodeResponse = IdentityControllerRequestSmsLoginCodeResponses[keyof IdentityControllerRequestSmsLoginCodeResponses];

export type IdentityControllerConfirmSmsLoginData = {
    body: ConfirmSmsLoginDtoWritable;
    path?: never;
    query?: never;
    url: '/api/v1/auth/user/sms-login/confirm';
};

export type IdentityControllerConfirmSmsLoginResponses = {
    201: CreatedSessionDto;
};

export type IdentityControllerConfirmSmsLoginResponse = IdentityControllerConfirmSmsLoginResponses[keyof IdentityControllerConfirmSmsLoginResponses];

export type IdentityControllerCreateUserPasswordSessionData = {
    body: CreateUserPasswordSessionDtoWritable;
    path?: never;
    query?: never;
    url: '/api/v1/auth/sessions';
};

export type IdentityControllerCreateUserPasswordSessionResponses = {
    201: CreatedSessionDto;
};

export type IdentityControllerCreateUserPasswordSessionResponse = IdentityControllerCreateUserPasswordSessionResponses[keyof IdentityControllerCreateUserPasswordSessionResponses];

export type IdentityControllerCreatePlatformSessionData = {
    body: CreatePlatformSessionDtoWritable;
    path?: never;
    query?: never;
    url: '/api/v1/auth/platform/sessions';
};

export type IdentityControllerCreatePlatformSessionResponses = {
    201: CreatedSessionDto;
};

export type IdentityControllerCreatePlatformSessionResponse = IdentityControllerCreatePlatformSessionResponses[keyof IdentityControllerCreatePlatformSessionResponses];

export type IdentityControllerStartPlatformEnrollmentData = {
    body: StartPlatformEnrollmentDtoWritable;
    path?: never;
    query?: never;
    url: '/api/v1/auth/platform/enrollments';
};

export type IdentityControllerStartPlatformEnrollmentResponses = {
    201: StartedPlatformEnrollmentDto;
};

export type IdentityControllerStartPlatformEnrollmentResponse = IdentityControllerStartPlatformEnrollmentResponses[keyof IdentityControllerStartPlatformEnrollmentResponses];

export type IdentityControllerConfirmPlatformEnrollmentData = {
    body: ConfirmPlatformEnrollmentDto;
    path?: never;
    query?: never;
    url: '/api/v1/auth/platform/enrollments/confirm';
};

export type IdentityControllerConfirmPlatformEnrollmentResponses = {
    201: ConfirmedPlatformEnrollmentDto;
};

export type IdentityControllerConfirmPlatformEnrollmentResponse = IdentityControllerConfirmPlatformEnrollmentResponses[keyof IdentityControllerConfirmPlatformEnrollmentResponses];

export type IdentityControllerFinishPlatformEnrollmentData = {
    body: FinishPlatformEnrollmentDtoWritable;
    path?: never;
    query?: never;
    url: '/api/v1/auth/platform/enrollments/finish';
};

export type IdentityControllerFinishPlatformEnrollmentResponses = {
    201: CreatedSessionDto;
};

export type IdentityControllerFinishPlatformEnrollmentResponse = IdentityControllerFinishPlatformEnrollmentResponses[keyof IdentityControllerFinishPlatformEnrollmentResponses];

export type IdentityControllerRevokeCurrentSessionData = {
    body?: never;
    headers: {
        'x-csrf-token': string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/auth/sessions/current';
};

export type IdentityControllerRevokeCurrentSessionResponses = {
    204: void;
};

export type IdentityControllerRevokeCurrentSessionResponse = IdentityControllerRevokeCurrentSessionResponses[keyof IdentityControllerRevokeCurrentSessionResponses];

export type IdentityControllerCurrentSessionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/sessions/current';
};

export type IdentityControllerCurrentSessionResponses = {
    200: SessionAccountDto;
};

export type IdentityControllerCurrentSessionResponse = IdentityControllerCurrentSessionResponses[keyof IdentityControllerCurrentSessionResponses];

export type PhoneChangeControllerRequestOldCodeData = {
    body: RequestPhoneChangeOldCodeDto;
    headers: {
        'x-csrf-token': string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/account/phone-change/old-phone/code';
};

export type PhoneChangeControllerRequestOldCodeResponses = {
    200: ActivationCodeDeliveryDto;
};

export type PhoneChangeControllerRequestOldCodeResponse = PhoneChangeControllerRequestOldCodeResponses[keyof PhoneChangeControllerRequestOldCodeResponses];

export type PhoneChangeControllerRequestNewCodeData = {
    body: RequestPhoneChangeNewCodeDto;
    headers: {
        'x-csrf-token': string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/account/phone-change/new-phone/code';
};

export type PhoneChangeControllerRequestNewCodeResponses = {
    200: ActivationCodeDeliveryDto;
};

export type PhoneChangeControllerRequestNewCodeResponse = PhoneChangeControllerRequestNewCodeResponses[keyof PhoneChangeControllerRequestNewCodeResponses];

export type PhoneChangeControllerConfirmData = {
    body: ConfirmPhoneChangeDto;
    headers: {
        'x-csrf-token': string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/account/phone-change/confirm';
};

export type PhoneChangeControllerConfirmResponses = {
    200: PhoneChangeConfirmResultDto;
};

export type PhoneChangeControllerConfirmResponse = PhoneChangeControllerConfirmResponses[keyof PhoneChangeControllerConfirmResponses];

export type PlatformAccountControllerCreateData = {
    body: CreatePlatformAccountDto;
    headers: {
        'x-csrf-token': string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/platform/accounts';
};

export type PlatformAccountControllerCreateResponses = {
    201: CreatedPlatformAccountDto;
};

export type PlatformAccountControllerCreateResponse = PlatformAccountControllerCreateResponses[keyof PlatformAccountControllerCreateResponses];

export type PlatformAccountControllerDisableData = {
    body?: never;
    headers: {
        'x-csrf-token': string;
    };
    path: {
        accountId: unknown;
    };
    query?: never;
    url: '/api/v1/platform/accounts/{accountId}/disable';
};

export type PlatformAccountControllerDisableResponses = {
    204: void;
};

export type PlatformAccountControllerDisableResponse = PlatformAccountControllerDisableResponses[keyof PlatformAccountControllerDisableResponses];

export type PlatformAccountControllerResetTotpData = {
    body?: never;
    headers: {
        'x-csrf-token': string;
    };
    path: {
        accountId: unknown;
    };
    query?: never;
    url: '/api/v1/platform/accounts/{accountId}/totp-reset';
};

export type PlatformAccountControllerResetTotpResponses = {
    204: void;
};

export type PlatformAccountControllerResetTotpResponse = PlatformAccountControllerResetTotpResponses[keyof PlatformAccountControllerResetTotpResponses];

export type PlatformRegistrationControllerRequestCodeData = {
    body: RequestRegistrationCodeDto;
    path?: never;
    query?: never;
    url: '/api/v1/account/platform-registration/codes';
};

export type PlatformRegistrationControllerRequestCodeResponses = {
    200: ActivationCodeDeliveryDto;
};

export type PlatformRegistrationControllerRequestCodeResponse = PlatformRegistrationControllerRequestCodeResponses[keyof PlatformRegistrationControllerRequestCodeResponses];

export type PlatformRegistrationControllerConfirmData = {
    body: ConfirmRegistrationDto;
    path?: never;
    query?: never;
    url: '/api/v1/account/platform-registration/confirm';
};

export type PlatformRegistrationControllerConfirmResponses = {
    201: CreatedSessionDto;
};

export type PlatformRegistrationControllerConfirmResponse = PlatformRegistrationControllerConfirmResponses[keyof PlatformRegistrationControllerConfirmResponses];

export type StudentProfileControllerGetMyProfileData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/account/me/profile';
};

export type StudentProfileControllerGetMyProfileResponses = {
    200: MyProfileDto;
};

export type StudentProfileControllerGetMyProfileResponse = StudentProfileControllerGetMyProfileResponses[keyof StudentProfileControllerGetMyProfileResponses];

export type StudentProfileControllerCompleteFirstLoginData = {
    body: CompleteFirstLoginProfileDto;
    headers: {
        'x-csrf-token': string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/account/me/profile/completion';
};

export type StudentProfileControllerCompleteFirstLoginResponses = {
    200: MyProfileDto;
};

export type StudentProfileControllerCompleteFirstLoginResponse = StudentProfileControllerCompleteFirstLoginResponses[keyof StudentProfileControllerCompleteFirstLoginResponses];

export type StudentProfileControllerUpdateResidentCityData = {
    body: UpdateResidentCityDto;
    headers: {
        'x-csrf-token': string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/account/me/resident-city';
};

export type StudentProfileControllerUpdateResidentCityResponses = {
    204: void;
};

export type StudentProfileControllerUpdateResidentCityResponse = StudentProfileControllerUpdateResidentCityResponses[keyof StudentProfileControllerUpdateResidentCityResponses];

export type StudentProfileControllerSelfCorrectProfileData = {
    body: SelfCorrectProfileDto;
    headers: {
        'x-csrf-token': string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/account/me/platform-profile';
};

export type StudentProfileControllerSelfCorrectProfileResponses = {
    200: MyProfileDto;
};

export type StudentProfileControllerSelfCorrectProfileResponse = StudentProfileControllerSelfCorrectProfileResponses[keyof StudentProfileControllerSelfCorrectProfileResponses];

export type StudentSecurityControllerDisableStudentTotpData = {
    body?: never;
    headers: {
        'x-csrf-token': string;
    };
    path: {
        accountId: unknown;
    };
    query?: never;
    url: '/api/v1/university/students/{accountId}/totp-disable';
};

export type StudentSecurityControllerDisableStudentTotpResponses = {
    204: void;
};

export type StudentSecurityControllerDisableStudentTotpResponse = StudentSecurityControllerDisableStudentTotpResponses[keyof StudentSecurityControllerDisableStudentTotpResponses];

export type OrganizationControllerListTenantsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/organizations';
};

export type OrganizationControllerListTenantsResponses = {
    200: Array<TenantSummaryDto>;
};

export type OrganizationControllerListTenantsResponse = OrganizationControllerListTenantsResponses[keyof OrganizationControllerListTenantsResponses];

export type OrganizationControllerAdministrativeDivisionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/organizations/administrative-divisions';
};

export type OrganizationControllerAdministrativeDivisionsResponses = {
    200: Array<AdministrativeDivisionDto>;
};

export type OrganizationControllerAdministrativeDivisionsResponse = OrganizationControllerAdministrativeDivisionsResponses[keyof OrganizationControllerAdministrativeDivisionsResponses];

export type OrganizationControllerEnterpriseNatureTagsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/organizations/enterprise-nature-tags';
};

export type OrganizationControllerEnterpriseNatureTagsResponses = {
    200: Array<EnterpriseNatureTagDto>;
};

export type OrganizationControllerEnterpriseNatureTagsResponse = OrganizationControllerEnterpriseNatureTagsResponses[keyof OrganizationControllerEnterpriseNatureTagsResponses];

export type OrganizationControllerIndustryCategoriesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/organizations/industry-categories';
};

export type OrganizationControllerIndustryCategoriesResponses = {
    200: Array<IndustryCategoryDto>;
};

export type OrganizationControllerIndustryCategoriesResponse = OrganizationControllerIndustryCategoriesResponses[keyof OrganizationControllerIndustryCategoriesResponses];

export type OrganizationControllerCurrentData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/organizations/current';
};

export type OrganizationControllerCurrentResponses = {
    200: CurrentOrganizationDto;
};

export type OrganizationControllerCurrentResponse = OrganizationControllerCurrentResponses[keyof OrganizationControllerCurrentResponses];

export type OrganizationControllerCreateUniversityData = {
    body: CreateUniversityDto;
    headers: {
        'x-csrf-token': string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/organizations/universities';
};

export type OrganizationControllerCreateUniversityResponses = {
    201: CreatedTenantDto;
};

export type OrganizationControllerCreateUniversityResponse = OrganizationControllerCreateUniversityResponses[keyof OrganizationControllerCreateUniversityResponses];

export type OrganizationControllerAddUniversityAdminData = {
    body: InitialTenantAdminDto;
    headers: {
        'x-csrf-token': string;
    };
    path: {
        tenantId: unknown;
    };
    query?: never;
    url: '/api/v1/organizations/universities/{tenantId}/admins';
};

export type OrganizationControllerAddUniversityAdminResponses = {
    201: CreatedUniversityAdminDto;
};

export type OrganizationControllerAddUniversityAdminResponse = OrganizationControllerAddUniversityAdminResponses[keyof OrganizationControllerAddUniversityAdminResponses];

export type OrganizationControllerCreateEnterpriseData = {
    body: CreateEnterpriseDto;
    headers: {
        'x-csrf-token': string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/organizations/enterprises';
};

export type OrganizationControllerCreateEnterpriseResponses = {
    201: CreatedTenantDto;
};

export type OrganizationControllerCreateEnterpriseResponse = OrganizationControllerCreateEnterpriseResponses[keyof OrganizationControllerCreateEnterpriseResponses];

export type OrganizationControllerAddEnterpriseAdminData = {
    body: InitialTenantAdminDto;
    headers: {
        'x-csrf-token': string;
    };
    path: {
        tenantId: unknown;
    };
    query?: never;
    url: '/api/v1/organizations/enterprises/{tenantId}/admins';
};

export type OrganizationControllerAddEnterpriseAdminResponses = {
    201: CreatedUniversityAdminDto;
};

export type OrganizationControllerAddEnterpriseAdminResponse = OrganizationControllerAddEnterpriseAdminResponses[keyof OrganizationControllerAddEnterpriseAdminResponses];

export type OrganizationControllerCreateGovernmentData = {
    body: CreateGovernmentDto;
    headers: {
        'x-csrf-token': string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/organizations/governments';
};

export type OrganizationControllerCreateGovernmentResponses = {
    201: CreatedTenantDto;
};

export type OrganizationControllerCreateGovernmentResponse = OrganizationControllerCreateGovernmentResponses[keyof OrganizationControllerCreateGovernmentResponses];

export type OrganizationControllerAddGovernmentAdminData = {
    body: InitialTenantAdminDto;
    headers: {
        'x-csrf-token': string;
    };
    path: {
        tenantId: unknown;
    };
    query?: never;
    url: '/api/v1/organizations/governments/{tenantId}/admins';
};

export type OrganizationControllerAddGovernmentAdminResponses = {
    201: CreatedUniversityAdminDto;
};

export type OrganizationControllerAddGovernmentAdminResponse = OrganizationControllerAddGovernmentAdminResponses[keyof OrganizationControllerAddGovernmentAdminResponses];

export type OrganizationControllerReplaceGovernmentScopesData = {
    body: ReplaceGovernmentScopesDto;
    headers: {
        'x-csrf-token': string;
    };
    path: {
        tenantId: unknown;
    };
    query?: never;
    url: '/api/v1/organizations/governments/{tenantId}/university-scopes';
};

export type OrganizationControllerReplaceGovernmentScopesResponses = {
    204: void;
};

export type OrganizationControllerReplaceGovernmentScopesResponse = OrganizationControllerReplaceGovernmentScopesResponses[keyof OrganizationControllerReplaceGovernmentScopesResponses];

export type PublicOnboardingLeadControllerSubmitData = {
    body: SubmitOnboardingLeadDto;
    path?: never;
    query?: never;
    url: '/api/v1/public/onboarding-leads';
};

export type PublicOnboardingLeadControllerSubmitResponses = {
    201: OnboardingLeadDto;
};

export type PublicOnboardingLeadControllerSubmitResponse = PublicOnboardingLeadControllerSubmitResponses[keyof PublicOnboardingLeadControllerSubmitResponses];

export type OrganizationOnboardingLeadControllerListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/organizations/onboarding-leads';
};

export type OrganizationOnboardingLeadControllerListResponses = {
    200: Array<OnboardingLeadDto>;
};

export type OrganizationOnboardingLeadControllerListResponse = OrganizationOnboardingLeadControllerListResponses[keyof OrganizationOnboardingLeadControllerListResponses];

export type OrganizationOnboardingLeadControllerUpdateStatusData = {
    body: UpdateOnboardingLeadStatusDto;
    headers: {
        'x-csrf-token': string;
    };
    path: {
        id: unknown;
    };
    query?: never;
    url: '/api/v1/organizations/onboarding-leads/{id}';
};

export type OrganizationOnboardingLeadControllerUpdateStatusResponses = {
    200: OnboardingLeadDto;
};

export type OrganizationOnboardingLeadControllerUpdateStatusResponse = OrganizationOnboardingLeadControllerUpdateStatusResponses[keyof OrganizationOnboardingLeadControllerUpdateStatusResponses];

export type UniversityOrganizationControllerOrgTreeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/university/org-tree';
};

export type UniversityOrganizationControllerOrgTreeResponses = {
    200: UniversityOrgTreeDto;
};

export type UniversityOrganizationControllerOrgTreeResponse = UniversityOrganizationControllerOrgTreeResponses[keyof UniversityOrganizationControllerOrgTreeResponses];

export type UniversityOrganizationControllerCreateCampusData = {
    body: CreateCampusDto;
    headers: {
        'x-csrf-token': string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/university/campuses';
};

export type UniversityOrganizationControllerCreateCampusResponses = {
    201: CampusDto;
};

export type UniversityOrganizationControllerCreateCampusResponse = UniversityOrganizationControllerCreateCampusResponses[keyof UniversityOrganizationControllerCreateCampusResponses];

export type UniversityOrganizationControllerCreateCollegeData = {
    body: CreateCollegeDto;
    headers: {
        'x-csrf-token': string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/university/colleges';
};

export type UniversityOrganizationControllerCreateCollegeResponses = {
    201: CollegeSummaryDto;
};

export type UniversityOrganizationControllerCreateCollegeResponse = UniversityOrganizationControllerCreateCollegeResponses[keyof UniversityOrganizationControllerCreateCollegeResponses];

export type UniversityOrganizationControllerReplaceCollegeCampusesData = {
    body: ReplaceCollegeCampusesDto;
    headers: {
        'x-csrf-token': string;
    };
    path: {
        collegeId: unknown;
    };
    query?: never;
    url: '/api/v1/university/colleges/{collegeId}/campuses';
};

export type UniversityOrganizationControllerReplaceCollegeCampusesResponses = {
    204: void;
};

export type UniversityOrganizationControllerReplaceCollegeCampusesResponse = UniversityOrganizationControllerReplaceCollegeCampusesResponses[keyof UniversityOrganizationControllerReplaceCollegeCampusesResponses];

export type UniversityOrganizationControllerCreateMajorData = {
    body: CreateMajorDto;
    headers: {
        'x-csrf-token': string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/university/majors';
};

export type UniversityOrganizationControllerCreateMajorResponses = {
    201: MajorSummaryDto;
};

export type UniversityOrganizationControllerCreateMajorResponse = UniversityOrganizationControllerCreateMajorResponses[keyof UniversityOrganizationControllerCreateMajorResponses];

export type UniversityOrganizationControllerCreateClassData = {
    body: CreateClassDto;
    headers: {
        'x-csrf-token': string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/university/classes';
};

export type UniversityOrganizationControllerCreateClassResponses = {
    201: ClassSummaryDto;
};

export type UniversityOrganizationControllerCreateClassResponse = UniversityOrganizationControllerCreateClassResponses[keyof UniversityOrganizationControllerCreateClassResponses];

export type UniversityOrganizationControllerAssignClassCounselorData = {
    body: AssignClassCounselorDto;
    headers: {
        'x-csrf-token': string;
    };
    path: {
        classId: unknown;
    };
    query?: never;
    url: '/api/v1/university/classes/{classId}/counselor';
};

export type UniversityOrganizationControllerAssignClassCounselorResponses = {
    200: ClassSummaryDto;
};

export type UniversityOrganizationControllerAssignClassCounselorResponse = UniversityOrganizationControllerAssignClassCounselorResponses[keyof UniversityOrganizationControllerAssignClassCounselorResponses];

export type UniversityOrganizationControllerCreateMemberData = {
    body: CreateUniversityMemberDto;
    headers: {
        'x-csrf-token': string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/university/members';
};

export type UniversityOrganizationControllerCreateMemberResponses = {
    201: UniversityMemberDto;
};

export type UniversityOrganizationControllerCreateMemberResponse = UniversityOrganizationControllerCreateMemberResponses[keyof UniversityOrganizationControllerCreateMemberResponses];

export type UniversityStaffControllerHandoverData = {
    body: HandoverUniversityMemberDto;
    headers: {
        'x-csrf-token': string;
    };
    path: {
        membershipId: unknown;
    };
    query?: never;
    url: '/api/v1/university/members/{membershipId}/handover';
};

export type UniversityStaffControllerHandoverResponses = {
    200: StaffHandoverResultDto;
};

export type UniversityStaffControllerHandoverResponse = UniversityStaffControllerHandoverResponses[keyof UniversityStaffControllerHandoverResponses];

export type UniversityStaffControllerDisableData = {
    body?: never;
    headers: {
        'x-csrf-token': string;
    };
    path: {
        membershipId: unknown;
    };
    query?: never;
    url: '/api/v1/university/members/{membershipId}/disable';
};

export type UniversityStaffControllerDisableResponses = {
    204: void;
};

export type UniversityStaffControllerDisableResponse = UniversityStaffControllerDisableResponses[keyof UniversityStaffControllerDisableResponses];

export type UniversityStaffControllerListPendingClassTransfersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/university/class-transfers';
};

export type UniversityStaffControllerListPendingClassTransfersResponses = {
    200: Array<ClassTransferRequestDto>;
};

export type UniversityStaffControllerListPendingClassTransfersResponse = UniversityStaffControllerListPendingClassTransfersResponses[keyof UniversityStaffControllerListPendingClassTransfersResponses];

export type UniversityStaffControllerResolveClassTransferData = {
    body: ResolveClassTransferDto;
    headers: {
        'x-csrf-token': string;
    };
    path: {
        id: unknown;
    };
    query?: never;
    url: '/api/v1/university/class-transfers/{id}/resolve';
};

export type UniversityStaffControllerResolveClassTransferResponses = {
    200: ClassTransferRequestDto;
};

export type UniversityStaffControllerResolveClassTransferResponse = UniversityStaffControllerResolveClassTransferResponses[keyof UniversityStaffControllerResolveClassTransferResponses];

export type StudentClassTransferControllerListMineData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/account/me/class-transfers';
};

export type StudentClassTransferControllerListMineResponses = {
    200: Array<ClassTransferRequestDto>;
};

export type StudentClassTransferControllerListMineResponse = StudentClassTransferControllerListMineResponses[keyof StudentClassTransferControllerListMineResponses];

export type StudentClassTransferControllerCreateData = {
    body: CreateClassTransferDto;
    headers: {
        'x-csrf-token': string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/account/me/class-transfers';
};

export type StudentClassTransferControllerCreateResponses = {
    201: ClassTransferRequestDto;
};

export type StudentClassTransferControllerCreateResponse = StudentClassTransferControllerCreateResponses[keyof StudentClassTransferControllerCreateResponses];

export type CounselorStudentImportControllerImportStudentsData = {
    body: ImportClassStudentsDto;
    headers: {
        'x-csrf-token': string;
    };
    path: {
        classId: unknown;
    };
    query?: never;
    url: '/api/v1/university/classes/{classId}/students/import';
};

export type CounselorStudentImportControllerImportStudentsResponses = {
    201: StudentImportResultDto;
};

export type CounselorStudentImportControllerImportStudentsResponse = CounselorStudentImportControllerImportStudentsResponses[keyof CounselorStudentImportControllerImportStudentsResponses];

export type UniversityStudentControllerListClassStudentsData = {
    body?: never;
    path: {
        classId: unknown;
    };
    query?: never;
    url: '/api/v1/university/classes/{classId}/students';
};

export type UniversityStudentControllerListClassStudentsResponses = {
    200: Array<StudentSummaryDto>;
};

export type UniversityStudentControllerListClassStudentsResponse = UniversityStudentControllerListClassStudentsResponses[keyof UniversityStudentControllerListClassStudentsResponses];

export type UniversityStudentControllerCreateStudentData = {
    body: CreateClassStudentDto;
    headers: {
        'x-csrf-token': string;
    };
    path: {
        classId: unknown;
    };
    query?: never;
    url: '/api/v1/university/classes/{classId}/students';
};

export type UniversityStudentControllerCreateStudentResponses = {
    201: StudentSummaryDto;
};

export type UniversityStudentControllerCreateStudentResponse = UniversityStudentControllerCreateStudentResponses[keyof UniversityStudentControllerCreateStudentResponses];

export type UniversityStudentControllerGraduateStudentsData = {
    body: GraduateClassStudentsDto;
    headers: {
        'x-csrf-token': string;
    };
    path: {
        classId: unknown;
    };
    query?: never;
    url: '/api/v1/university/classes/{classId}/students/graduate';
};

export type UniversityStudentControllerGraduateStudentsResponses = {
    200: Array<StudentSummaryDto>;
};

export type UniversityStudentControllerGraduateStudentsResponse = UniversityStudentControllerGraduateStudentsResponses[keyof UniversityStudentControllerGraduateStudentsResponses];

export type UniversityStudentControllerSuspendStudentData = {
    body?: never;
    headers: {
        'x-csrf-token': string;
    };
    path: {
        accountId: unknown;
    };
    query?: never;
    url: '/api/v1/university/students/{accountId}/suspend';
};

export type UniversityStudentControllerSuspendStudentResponses = {
    204: void;
};

export type UniversityStudentControllerSuspendStudentResponse = UniversityStudentControllerSuspendStudentResponses[keyof UniversityStudentControllerSuspendStudentResponses];

export type UniversityStudentControllerRestoreStudentData = {
    body?: never;
    headers: {
        'x-csrf-token': string;
    };
    path: {
        accountId: unknown;
    };
    query?: never;
    url: '/api/v1/university/students/{accountId}/restore';
};

export type UniversityStudentControllerRestoreStudentResponses = {
    204: void;
};

export type UniversityStudentControllerRestoreStudentResponse = UniversityStudentControllerRestoreStudentResponses[keyof UniversityStudentControllerRestoreStudentResponses];

export type UniversityStudentControllerDeregisterStudentData = {
    body?: never;
    headers: {
        'x-csrf-token': string;
    };
    path: {
        accountId: unknown;
    };
    query?: never;
    url: '/api/v1/university/students/{accountId}/deregister';
};

export type UniversityStudentControllerDeregisterStudentResponses = {
    204: void;
};

export type UniversityStudentControllerDeregisterStudentResponse = UniversityStudentControllerDeregisterStudentResponses[keyof UniversityStudentControllerDeregisterStudentResponses];

export type UniversityStudentControllerCorrectStudentIdentityData = {
    body: CorrectStudentIdentityDto;
    headers: {
        'x-csrf-token': string;
    };
    path: {
        accountId: unknown;
    };
    query?: never;
    url: '/api/v1/university/students/{accountId}/identity';
};

export type UniversityStudentControllerCorrectStudentIdentityResponses = {
    200: StudentSummaryDto;
};

export type UniversityStudentControllerCorrectStudentIdentityResponse = UniversityStudentControllerCorrectStudentIdentityResponses[keyof UniversityStudentControllerCorrectStudentIdentityResponses];

export type EnterpriseOrganizationControllerGetOrgData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/enterprise/org';
};

export type EnterpriseOrganizationControllerGetOrgResponses = {
    200: EnterpriseOrgDto;
};

export type EnterpriseOrganizationControllerGetOrgResponse = EnterpriseOrganizationControllerGetOrgResponses[keyof EnterpriseOrganizationControllerGetOrgResponses];

export type EnterpriseOrganizationControllerCreateDepartmentData = {
    body: CreateEnterpriseDepartmentDto;
    headers: {
        'x-csrf-token': string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/enterprise/departments';
};

export type EnterpriseOrganizationControllerCreateDepartmentResponses = {
    201: EnterpriseDepartmentDto;
};

export type EnterpriseOrganizationControllerCreateDepartmentResponse = EnterpriseOrganizationControllerCreateDepartmentResponses[keyof EnterpriseOrganizationControllerCreateDepartmentResponses];

export type EnterpriseOrganizationControllerReplaceLocationsData = {
    body: ReplaceEnterpriseLocationsDto;
    headers: {
        'x-csrf-token': string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/enterprise/locations';
};

export type EnterpriseOrganizationControllerReplaceLocationsResponses = {
    204: void;
};

export type EnterpriseOrganizationControllerReplaceLocationsResponse = EnterpriseOrganizationControllerReplaceLocationsResponses[keyof EnterpriseOrganizationControllerReplaceLocationsResponses];

export type EnterpriseOrganizationControllerCreateMemberData = {
    body: CreateEnterpriseMemberDto;
    headers: {
        'x-csrf-token': string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/enterprise/members';
};

export type EnterpriseOrganizationControllerCreateMemberResponses = {
    201: EnterpriseMemberDto;
};

export type EnterpriseOrganizationControllerCreateMemberResponse = EnterpriseOrganizationControllerCreateMemberResponses[keyof EnterpriseOrganizationControllerCreateMemberResponses];

export type EnterpriseOrganizationControllerDisableMemberData = {
    body?: never;
    headers: {
        'x-csrf-token': string;
    };
    path: {
        membershipId: unknown;
    };
    query?: never;
    url: '/api/v1/enterprise/members/{membershipId}/disable';
};

export type EnterpriseOrganizationControllerDisableMemberResponses = {
    204: void;
};

export type EnterpriseOrganizationControllerDisableMemberResponse = EnterpriseOrganizationControllerDisableMemberResponses[keyof EnterpriseOrganizationControllerDisableMemberResponses];

export type GovernmentOrganizationControllerListMembersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/government/members';
};

export type GovernmentOrganizationControllerListMembersResponses = {
    200: Array<GovernmentMemberDto>;
};

export type GovernmentOrganizationControllerListMembersResponse = GovernmentOrganizationControllerListMembersResponses[keyof GovernmentOrganizationControllerListMembersResponses];

export type GovernmentOrganizationControllerCreateMemberData = {
    body: CreateGovernmentMemberDto;
    headers: {
        'x-csrf-token': string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/government/members';
};

export type GovernmentOrganizationControllerCreateMemberResponses = {
    201: GovernmentMemberDto;
};

export type GovernmentOrganizationControllerCreateMemberResponse = GovernmentOrganizationControllerCreateMemberResponses[keyof GovernmentOrganizationControllerCreateMemberResponses];

export type GovernmentOrganizationControllerDisableMemberData = {
    body?: never;
    headers: {
        'x-csrf-token': string;
    };
    path: {
        membershipId: unknown;
    };
    query?: never;
    url: '/api/v1/government/members/{membershipId}/disable';
};

export type GovernmentOrganizationControllerDisableMemberResponses = {
    204: void;
};

export type GovernmentOrganizationControllerDisableMemberResponse = GovernmentOrganizationControllerDisableMemberResponses[keyof GovernmentOrganizationControllerDisableMemberResponses];

export type PublicAcademyControllerListCampusesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/platform/public-academy/campuses';
};

export type PublicAcademyControllerListCampusesResponses = {
    200: Array<PublicAcademyCampusDto>;
};

export type PublicAcademyControllerListCampusesResponse = PublicAcademyControllerListCampusesResponses[keyof PublicAcademyControllerListCampusesResponses];

export type PublicAcademyControllerSetCampusStatusData = {
    body: SetPublicAcademyCampusStatusDto;
    headers: {
        'x-csrf-token': string;
    };
    path: {
        campusId: unknown;
    };
    query?: never;
    url: '/api/v1/platform/public-academy/campuses/{campusId}';
};

export type PublicAcademyControllerSetCampusStatusResponses = {
    200: PublicAcademyCampusDto;
};

export type PublicAcademyControllerSetCampusStatusResponse = PublicAcademyControllerSetCampusStatusResponses[keyof PublicAcademyControllerSetCampusStatusResponses];
